Sync most changes with RBOS
git-svn-id: svn://svn.code.sf.net/p/linuxrcd/code@244 3df0df1f-9518-46d5-b0fc-6e62cabb456f

diff --git a/linuxrcd_files/usr/bin/compile_all b/linuxrcd_files/usr/bin/compile_all
--- a/linuxrcd_files/usr/bin/compile_all
+++ b/linuxrcd_files/usr/bin/compile_all
@@ -21,57 +21,61 @@
 
 argument=$1
 
+CLEANUPOVERLAY=1
 export MAKEDEBS=1
 
-
-#build these packages in this order. # symbol is a comment
-if [[ ! -e /usr/lib/casper ]]
-then
-  COMPILELIST+="casper"
-  COMPILELIST+=$'\n'
-fi
-
-if [[ ! -e /usr/share/initramfs-tools/hooks/lupin_casper ]]
-then
-  COMPILELIST+="lupin"
-  COMPILELIST+=$'\n'
-fi
-
-echo "$COMPILELIST" | awk -F "#" '{print $1}' | while read BUILDNAME
-do
-
+function CompilePackage
+{
+  BUILDNAME=$1
   #compile_all is running to download the source
   if [[ "$argument" == download-only ]]
   then
     echo "Downloading/updating $BUILDNAME source"
-    "/usr/bin/Compile/$BUILDNAME" download-only 2>&1 
+    build_core buildspec "/usr/bin/Compile/$BUILDNAME" download-only 2>&1 
   fi
 
   #compile_all is running to build the source
   if [[ "$argument" == build-only ]]
   then
+    #Cleanup any files in the srcbuild_overlay from the last build
     echo "building $BUILDNAME"
-    "/usr/bin/Compile/$BUILDNAME" build-only 2>&1
+    build_core buildspec "/usr/bin/Compile/$BUILDNAME" build-only 2>&1
+    if [[ $(mountpoint -q /tmp/srcbuild_overlay/; echo $?) == 0 && $CLEANUPOVERLAY == 1 ]]
+    then
+      rm -rf /tmp/srcbuild_overlay/*
+      mount -o remount /srcbuild/
+    fi
   fi
 
   #Install the smaller version of the package
   if [[ "$argument" == installsmallpackage ]]
   then
     echo "Attempting to install smaller version of $BUILDNAME"
-    "/usr/bin/Compile/$BUILDNAME" installsmallpackage 2>&1
+    build_core buildspec "/usr/bin/Compile/$BUILDNAME" installsmallpackage 2>&1
   fi
   
   #compile_all is running to clean the source
   if [[ "$argument" == clean ]]
   then
     echo "Cleaning $BUILDNAME"
-    "/usr/bin/Compile/$BUILDNAME" clean 2>&1
+    build_core buildspec "/usr/bin/Compile/$BUILDNAME" clean 2>&1
   fi
   
   #compile_all is running to download and build
   if [[ ! -n "$argument" ]]
   then
-    "/usr/bin/Compile/$BUILDNAME"
+    build_core buildspec "/usr/bin/Compile/$BUILDNAME"
   fi
+  
+}
 
-done
+#build these packages in this order.
+if [[ ! -e /usr/lib/casper ]]
+then
+  CompilePackage casper
+fi
+
+if [[ ! -e /usr/share/initramfs-tools/hooks/lupin_casper ]]
+then
+  CompilePackage lupin
+fi
